DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS listings CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE buyers (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
);


CREATE TABLE  listings (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnail_photo_url VARCHAR(255) NOT NULL,
  cover_photo_url VARCHAR(255) NOT NULL,
  date TIMESTAMP,
  price INTEGER NOT NULL DEFAULT 0,
  for_sale BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE sellers (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
  listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE
);


CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
  listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE
);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyer(id) ON DELETE CASCADE,
  seller_id INTEGER REFERENCES seller(id) ON DELETE CASCADE,
  title VARCHAR (255) NOT NULL,
  description text
);

