DROP TABLE IF EXISTS buyers CASCADE;
DROP TABLE IF EXISTS sellers CASCADE;
DROP TABLE IF EXISTS listings CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
CREATE TABLE buyers (
  id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE sellers (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE
);
CREATE TABLE  listings (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnail_photo_url VARCHAR(255),
  cover_photo_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  price INTEGER NOT NULL DEFAULT 0,
  for_sale BOOLEAN NOT NULL,
  seller_id INTEGER NOT NULL
);
CREATE TABLE favorites (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
  listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE
);
CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,
  buyer_id INTEGER REFERENCES buyers(id) ON DELETE CASCADE,
  seller_id INTEGER REFERENCES sellers(id) ON DELETE CASCADE,
  listing_id INTEGER REFERENCES listings(id) ON DELETE CASCADE,
  title VARCHAR (255) NOT NULL,
  description text,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE buyers
OWNER TO labber;
ALTER TABLE listings
OWNER TO labber;
ALTER TABLE sellers
OWNER TO labber;
ALTER TABLE favorites
OWNER TO labber;
ALTER TABLE messages
OWNER TO labber;
